### ISSUE TITLE
ephemeral containers - netdata does not cleanup

### ISSUE THREAD

**Issue by matejvelikonja** [firehol/netdata#1358]
I have a server on which I'm running docker engine and creating lots of docker containers. On that server netdata consumes huge amount of inodes. During the weekend netdata managed to consumed 15gb of disk space and quite a lot of inodes. The disk used is mostly in /var/cache/netdata. I guess netdata it's not cleaning unexisting docker container.
Is there something I can do or is this a bug in netdata?

**Comment by ktsaou** [comment]
hm... netdata does not remove charts by itself. So, it consumes memory too.
As I understand you have ephemeral docker containers that get started and stopped all the time, with random docker names every time. Right?

**Comment by matejvelikonja** [comment]
exactly, yes

**Comment by ktsaou** [comment]
Well, currently you have the following options:

1. in `/etc/netdata/netdata.conf` set `memory mode = ram` and restart netdata once per day, to make it free the RAM of unused charts. It will not use any disk.

2. set names to all your docker images, so that netdata will reuse the same chart memory when docker containers are restarted.

For sure, this should handled by netdata in a better way...

**Comment by matejvelikonja** [comment]
@ktsaou thanks for the work around tips, will try them out

**Comment by ktsaou** [comment]
I am switching to a bug. We really need to find a way to support ephemeral containers more efficiently.

**Comment by matejvelikonja** [comment]
since netdata only has 1 hour of history, could we just delete the containers older than 1 hour.

not a perfect solution, but it would solve many problems.

**Comment by ktsaou** [comment]
Yes, this is a solution. I have a problem with delete in general, which was partly solved with PR #1817 . I will try to give a solution soon (it bothers me too).

**Comment by ktsaou** [comment]
I have given a solution on PR #1875 for self-cleaning stopped network interfaces and containers.
Any testers available?

**Comment by ktsaou** [comment]
merged the fix.

**Comment by matejvelikonja** [comment]
The problem still persist in the latest commit aa6b96f.

In 2 hours netdata generated 5gb of cache.

I had a feeling, that some commits ago cleaning up worked, but it got broken afterwords.

**Comment by ktsaou** [comment]
hm... could please give me a procedure to reproduce it ?

netdata deletes the files one hour after the sending netdata disconnected, only if no one is viewing them. So, let's say it is 1 hour of inactivity. You can change this in netdata.conf

**Comment by matejvelikonja** [comment]
@ktsaou that's strage, today I have started netdata again and after couple of hours the disk space did not increase. so cleanup is working.

I will keep an eye on it and inform again if something strange happens again.

**Comment by ktsaou** [comment]
The only way for files to be left is to restart netdata during the 1 hour period. The new instance will not be aware of the left overs.

hm... I think I can fix that by deleting the files before the timeout when netdata exits... though they will still be left over if netdata crashes (which hopefully doesn't happen :-).

Another solution, would be to mark the files on disk for deletion, and have the new process remove them when it starts...

hm... let's trace your issue and I'll see how I can fix this rare case too.

**Comment by matejvelikonja** [comment]
Ok, it has worked for a day, and than today I have noticed, that netdata is again spamming the disk space.
I have also noticed that netdata was not running for the whole 3 days, but was restarted at least once (can't say if it was once of more time).
The oldest file in `/var/cache/netdata` is from `Mar 28 08:14`.

The graph is showing consumption of disk space from 3 days ago to today.
![screen shot 2017-03-31 at 09 18 23](https://cloud.githubusercontent.com/assets/1881087/24540342/0eda81da-15f3-11e7-87a2-941a9daf884e.png)

**Comment by matejvelikonja** [comment]
ok, this is getting quite a problem for me.

is it possible to disable container info collection for netdata?

**Comment by ktsaou** [comment]
You can disable `cgroups` in netdata.conf `[plugins]` section.
But, I'll need your help to settle this.

**Comment by matejvelikonja** [comment]
how can I be of any assistance?

**Comment by matejvelikonja** [comment]
could you just perform cleanup when netdata starts? I think it would solve the problem.

**Comment by ktsaou** [comment]
I'll add a few debug messages about this cleanup, so we will be able to see what it does and when. I'll do a few tests myself, and if I can't find it, I let you know.

Later today...

**Comment by ktsaou** [comment]
ok, I think I found the issue. I was deleting the files and under condition I was saving them again before freeing them from memory.

Now, I also cleanup obsolete directories from disk.

I am making a PR now. I also added some info lines to see it running.

**Comment by ktsaou** [comment]
merged it.
Please check now. It should be fixed. error.log should also print the deleted files.

**Comment by ktsaou** [comment]
@matejvelikonja did you have the chance to test it?

**Comment by matejvelikonja** [comment]
it has been running for one day now. but the netdata did not restart in the meanwhile and the cache is ok.

i will keep monitoring the situation.

**Comment by matejvelikonja** [comment]
It happened again, in 2 hours netdata consumed almost 10gb of disk space.
The oldest file is from `Apr 13 15:19` (15 hours ago).

**Comment by ktsaou** [comment]
Could you please post the full filename and grep for it in `error.log`?

**Comment by matejvelikonja** [comment]
sorry, already did the cleanup. will do it next time.

**Comment by ktsaou** [comment]
I suggest to run this:

```
find /var/cache/netdata/ -type f
```

And `diff` it when the problem occurs. It will reveal all the offending files.

**Comment by matejvelikonja** [comment]
The only thing that I remember is that it was some apache file. If this helps.
