### ISSUE TITLE
Invalid collecting and displaying data on statsd synthetic charts

### ISSUE THREAD

**Issue by VDigitall** [firehol/netdata#2253]
Hi,
I have a problem in follow case: If create chart with one or two dimensions on start, all work fine, but if later add new dimension or dimensions on this chart, they collecting via permanent increment. But on private chart all displaying fine. This issue appear in versions after v1.6.0-329-g654f847_rolling
![netdata_statsd_issue](https://cloud.githubusercontent.com/assets/6977678/26570022/cce3b9d8-4516-11e7-9535-710cbeedefa5.png)
Thanks for helping.

**Comment by ktsaou** [comment]
Hi, I don't get it. You are saying that when new dimensions are added to a synthetic chart, something gets permanently incremented, but you don't say which one. It would help if you could post the private chart too and pinpoint the dimension with the fault.

**Comment by VDigitall** [comment]
On first chart are dimension POST, PATCH, DELETE, HEAD
on second chart is dimension failed
```
[app]
  name = api
  metrics = api.*
  private charts = yes
  gaps when not collected = no
  memory mode = ram
  history = 60000

[request_methods]
  name = Requests methods
  title = Requests methods
  family = Request_methods
  context = api.request_methods
  units = requests
  type = line
  dimension = api.REQUEST_METHOD;POST POST last 1 1
  dimension = api.REQUEST_METHOD;PUT PUT last 1 1
  dimension = api.REQUEST_METHOD;PATCH PATCH last 1 1
  dimension = api.REQUEST_METHOD;DELETE DELETE last 1 1
  dimension = api.REQUEST_METHOD;GET GET last 1 1
  dimension = api.REQUEST_METHOD;HEAD HEAD last 1 1

[requests]
  name = Requests
  title = Requests
  family = Requests
  context = api.requests
  units = requests
  type = area
  dimension = api.MESSAGE_ID;error_handler failed last 1 1
  dimension = api.REQUEST_PROCESS_TIME;REQUEST_PROCESS_TIME total events 1 1
```
all this metrics send to statsd as counter

**Comment by ktsaou** [comment]
seems like a bug. Let me try to reproduce this to find the issue.

**Comment by ktsaou** [comment]
confirmed. I can reproduce it. Tracing the root cause...

**Comment by ktsaou** [comment]
fixed it.

For the record, this was introduced in my attempt to somehow maintain the order of dimesions in the charts. I decided then to add to synthetic dimensions all the dimensions when the chart is created. However, the algorithm of the dimensions is decided based on the statsd metric it is linked to. This introduced this problem. It worked for gauges (since the default algorithm for dimensions is `absolute`), but it did not work for counters and meters (the algorithm is `incremental`).

Thanks you for reporting it!

Will be merged with #2258

**Comment by ktsaou** [comment]
And... to reproduce it, I used this little script and your config:

```sh
#!/bin/bash

# all the metrics
metrics=('api.REQUEST_METHOD;POST' 'api.REQUEST_METHOD;PUT' 'api.REQUEST_METHOD;PATCH' 'api.REQUEST_METHOD;DELETE' 'api.REQUEST_METHOD;GET' 'api.REQUEST_METHOD;HEAD')

# add one metric every $dt seconds
dt=10

c=0
while [ 1 ]
do
    c=$((c + 1))
    
    m=$c
    [ $m -gt ${#metrics[@]} ] && m=${#metrics[@]}
    
    echo >&2 "Incrementing: ${metrics[@]:1:$m} for $dt seconds..."
    
    start=$(date +%s)
    end=$((start + dt))
    while [ $(date +%s) -le $end ]
    do
        for x in "${metrics[@]:1:$m}"
        do
            echo "${x}:1|c" | nc -u --send-only 127.0.0.1 8128
        done
    done
done

```

**Comment by ktsaou** [comment]
merged it.

**Comment by shellshock1953** [comment]
In 476 build I can still see this bug.
When I restart central netdata, synthetic charts is OK, but after a while, but when new dimensions appear, they start incrementing.
Maybe problem has place because of central netdata (I`m using master/slave streaming relations). 

![image](https://user-images.githubusercontent.com/9091084/26871786-0491b1fc-4b7d-11e7-9568-29497a5c4d50.png)

**Comment by ktsaou** [comment]
> Maybe problem has place because of central netdata (I`m using master/slave streaming relations).

Yes this is it. You are right. I will fix it later today. I have tried to generate all the dimensions of synthetic charts at once, when just one dimension is encountered. But as we see, this has several issues. So, I will remove this logic. Dimensions will be added only when they are collected. Unfortunately, this will influence the colors of the dimensions on the charts.

**Comment by ktsaou** [comment]
ok, I think I found a way not to do a step backwards.

It is currently in PR #2294 - can you test it? You need to update both the master and the slave.

Keep in mind this PR has also a change in the way memory modes are implemented. I have already tested memory mode = save (the default) and it works well. If you use any other mode (ram or map), please verify they work too.

**Comment by shellshock1953** [comment]
I installed netdata on master and clients from PR #2294 (now dashboard shows version as v1.0.0-4007-g533aafd_rolling)
Unfortunately bug is still here. (memory mode = save)

**Comment by ktsaou** [comment]
Could you please post one of the charts?
(the old data on this chart will be not affected, but the new data on the chart should be ok).

**Comment by shellshock1953** [comment]
After installing of netdata, I've removed cache from central netdata (just to be sure that old data doesn't affect to a new one)

![statsd_stuck2](https://user-images.githubusercontent.com/9091084/26930109-e5dc655c-4c64-11e7-86bc-957536532058.png)
![statsd_stuck1](https://user-images.githubusercontent.com/9091084/26930108-e5da9b32-4c64-11e7-8ddd-673afb4306d3.png)

**Comment by ktsaou** [comment]
Of course you are right.
Just pushed another fix. You need to apply this at the master. Can you test it?

**Comment by ktsaou** [comment]
ok, I verified it works now.

**Comment by shellshock1953** [comment]
Just test it too, seems to be working.
Thank you.

**Comment by ktsaou** [comment]
merged the fixes.
