### ISSUE TITLE
memory mode ram should use KSM when available

### ISSUE THREAD

**Issue by Ferroin** [firehol/netdata#2284]
Was just looking at one of my systems, and noticed something odd.  I've got `memory dedpulication = yes` set explicitly in the netdata configuration, and KSM is definitely enabled (I've got a custom init script to do so very early during boot which also fine-tunes some f the options, and it's obviously running since the settings all match what the script sets), but nothing appears to be getting touched by KSM (all the counters are zero).

At first I thought it might be something odd about this system (netdata is the only thing on the system I first noticed this on that marks memory for KSM), but I just checked on one of my other systems which is showing stats, and netdata doesn't appear to be affected by KSM there either (that system runs a bunch of QEMU VM's, and if I shut those down, all the KSM counters zero out until I start the VM's again), so it looks like something is causing netdata to not set MADV_MERGABLE on it's databases on these systems.

Both systems are running netdata 1.6.0 as packed in the Gentoo portage tree, and have stock configurations other than using the `ram` memory mode and having longer than normal history (6 hours on the first system, 24 on the second).

**Comment by Ferroin** [comment]
Apparently I had some over-zealous sysfs permissions restrictions left-over from a couple years ago when I was a lot more paranoid about system security, and /sys/kernel/mm/ksm was only accessible to root, and not being able to see that was causing netdata to not make the necessary madvise calls.

This leads me to the conclusion that the documentation for the memory deduplication is a bit misleading, and the implementation is slightly confusing.  The documentation [here](https://github.com/firehol/netdata/wiki/Configuration)  implies based on wording that `memory deduplication = yes` will cause netdata to make the calls unconditionally and handle the error if it fails, when what it actually does is look to see if ksmd is enabled and only make the calls if it is enabled.  More specifically, it explicitly says '_will_ offer up memory for deduplication'.

Quoting Documentation/vm/ksm.txt from the Linux sources:
>If KSM is not configured into the running kernel, madvise MADV_MERGEABLE
and MADV_UNMERGEABLE simply fail with EINVAL.  If the running kernel was
built with CONFIG_KSM=y, those calls will normally succeed: even if the
the KSM daemon is not currently running, MADV_MERGEABLE still registers
the range for whenever the KSM daemon is started; even if the range
cannot contain any pages which KSM could actually merge; even if
MADV_UNMERGEABLE is applied to a range which was never MADV_MERGEABLE.

Based on this, you have three cases:
1. KSM isn't built into the kernel, madvise(MADV_MERGABLE) will return EINVAL, and you can be certain KSM will never be enabled.
2. KSM is built into the kernel, but isn't enabled.  mavdise(MADV_MERGABLE) will return successfully, and there is a possibility that KSM will be enabled in the future.
3. KSM is built into the kernel, and is enabled.

Currently, netdata acts like case 2 is equivalent to case 1, despite it being arguably saner to treat it instead as equivalent to case 3.  In reality, case 2 is generally the most common for any arbitrary install, since most distro kernels have KSM built in, but the distro doesn't enable it by default (because very little uses it (vicious cycle there)).  The current netdata behavior of auto-detecting KSM when nothing is specified in the config make sense, but I would absolutely expect it to just make the madvise calls if `memory deduplication = yes` and just handle the error somehow (even just logging the error and continuing is fine).

**Comment by ktsaou** [comment]
Hi,

> The documentation here implies based on wording that memory deduplication = yes will cause netdata to make the calls unconditionally and handle the error if it fails, when what it actually does is look to see if ksmd is enabled and only make the calls if it is enabled.

netdata uses `MADV_MERGEABLE` unconditionally, when:

1. `option memory deduplication = yes`
2. `memory mode = save` (KSM is only available on `MAP_ANONYMOUS` pages which is only used in this mode)
3. `MADV_MERGEABLE` is defined at netdata compile time

netdata does not check for the existence of KSM. The files under `/sys/kernel/mm/ksm` are exclusively used by netdata for monitoring KSM. No other decision is taken based on their existence, absence, or content.

netdata always logs `madvise()` errors. But it requires `madvise()` to fail - [here is the proof](https://github.com/ktsaou/netdata/blob/a4a116788ef3e926049987f406eaa80890980db2/src/common.c#L1021-L1021). Of course it has a protection to log this only once (otherwise you would get thousands of such errors, one for each chart and dimension).

So, I understand that probably your previous security measures disabled KSM use for non-root users. qemu and the other programs normally run as root. netdata does not.

**Comment by Ferroin** [comment]
The `memory mode = save` requirement is what the issue was ultimately, I hadn't realized that I had changed both netdata.conf and the permissions on the sysfs files before re-testing.  That restriction really should be documented, but ideally there should be a way to use KSM without requiring the charts to be saved to persistent storage.

**Comment by ktsaou** [comment]
hm... you are right. Let me check how I can change that...

**Comment by Ferroin** [comment]
Looking at the code, my guess is that the easiest method would probably be to just convert the `memory mode = ram` case to try mmap instead of just using calloc unconditionally, but I may be missing something completely too (I hadn't realized from a cursory look that `memory mode = save` was needed for the KSM support either, so I wouldn't exactly trust my mental parsing of C code at the moment).

**Comment by ktsaou** [comment]
I implemented, but it is currently untested.
If you can test it, please do so, otherwise I will do it, probably tomorrow.

**Comment by ktsaou** [comment]
PR #2294

**Comment by Ferroin** [comment]
Cloning it to test right now, should have results for you within an hour.

**Comment by Ferroin** [comment]
It runs fine, but it's still not doing any memory deduplication on my system when `memory mode = ram`.  I double checked with `strace -f -e trace=madvise netdata -D`, and it appears that the madvise(MADV_MERGABLE) calls aren't happening (the only madvise calls I saw in fact were with MADV_DONTNEED).

**Comment by Ferroin** [comment]
Just finished a build with the new commits on the PR and started it up, it is in fact making the madvise calls correctly now.  I'll let you know if I see anything odd, but so far everything looks good.

**Comment by ktsaou** [comment]
Just pushed a few more.

It was finally a little bit more complex, because for `memory mode = ram`, I needed a way to use `calloc()` if `mmap()` fails for some reason.

So I ended up adding `memory mode = alloc` to properly handle this case. All memory modes except `none`, automatically fallback to `alloc` if `mmap()` fails for any reason. Memory mode `alloc` can also be given at the config file (which is the same to `ram` before this PR).

**Comment by Ferroin** [comment]
Sorry I took so long to get back on this.  Just finished checking with all the changes up through the fix for #2257, and it all still seems to work.  I also double checked that `memory mode = alloc` works as advertised as well.

**Comment by ktsaou** [comment]
perfect! thanks!

**Comment by ktsaou** [comment]
merged it.
