### ISSUE TITLE
Naming for Diskstats for Veritas Volume Manger disks

### ISSUE THREAD

**Issue by h0lzi** [firehol/netdata#4116]
Hi,
for normal diskstats for disks used under lvm the name for the metrics is e.g.
disk.*.rootvg_root_lv

![netdata_root_lv](https://user-images.githubusercontent.com/615675/45152629-e4d14000-b1d1-11e8-8ddd-b5898098d366.png)

We do use Veritas Volume Manger the naming is e.g. 
disk.*.vxvm3001

![oracle](https://user-images.githubusercontent.com/615675/45152712-282bae80-b1d2-11e8-8cae-060442997abd.png)

vxvm3001 is the "raw" name form /proc/diskstats.

It is put under the right mountpoint though.
I don't know where the translation is happening (did not check the code. maybe via /dev/mapper entry which Veritas Volume Manger disks don't have)

Since the stats are already shown under the correct mountpiont it would be nice if some renaming would happen also  as the info seems already present as it looks like.

Because in grafana working with vxvm3001 is not much help as I have no clue what the mountpoint is/was when looking at the stats.

**Comment by ktsaou** [comment]
Hi, netdata uses:

1. `/dev/mapper/`
2. `/dev/disk-by-label/`
3. `/dev/disk-by-id/`

I am not aware of the veritas volume manager disks. How do you find the names?

**Comment by h0lzi** [comment]
Well for Veritas Volume Manager it's

/dev/vx/dsk/*

e.g.

z1tl9165:/dev/vx/dsk/dg1607 # ls -larth
total 0
brw-------  1 root root 199, 6004 Sep  3 23:09 lvol004
brw-------  1 root root 199, 6003 Sep  3 23:09 lvol003
brw-------  1 root root 199, 6002 Sep  3 23:09 lvol002
brw-------  1 root root 199, 6001 Sep  3 23:09 lvol001
brw-------  1 root root 199, 6000 Sep  3 23:09 lvol000

where dg1607 is the diskgroup name in which the volume is located.
Both diskgroup name and volumes name can be whatever the user decides to set it to. 

z1tl9165:/dev/vx/dsk/dg1607 # 
z1tl9165:/dev/vx/dsk/dg1607 # cat /proc/diskstats |grep 6004
 199    6004 VxVM6004 116600 15566 94996083 646900 210592 23377 59848623 250168 0 859744 896640
z1tl9165:/dev/vx/dsk/dg1607 # df -h |grep 1607
/dev/vx/dsk/dg1607/lvol004        72G  8.3G   60G  13% /srv/oracle/was8e76e/flash
/dev/vx/dsk/dg1607/lvol002        32G   17G   15G  52% /srv/oracle/was8e76e/data
/dev/vx/dsk/dg1607/lvol003        16G   72M   15G   1% /srv/oracle/was8e76e/export
/dev/vx/dsk/dg1607/lvol000       512M   19M  463M   4% /opt/UC4clnt/z1ea1607
/dev/vx/dsk/dg1607/lvol001        10G  4.3G  5.5G  44% /srv/oracle/was8e76e/admin

so for the example above: vxvm3001

df -h |grep bestindw
/dev/vx/dsk/dg1603/lvol004       100G   95M   94G   1% /srv/oracle/bestindw/flash
/dev/vx/dsk/dg1603/lvol003        50G   82M   47G   1% /srv/oracle/bestindw/export
/dev/vx/dsk/dg1603/lvol001        30G   75M   29G   1% /srv/oracle/bestindw/admin
/dev/vx/dsk/dg1603/lvol002       330G  156M  310G   1% /srv/oracle/bestindw/data
z1tl9165:/dev/vx/dsk/dg1607 # cd ..
z1tl9165:/dev/vx/dsk # cd dg1603/
z1tl9165:/dev/vx/dsk/dg1603 # ls -larth
total 0
brw-------  1 root root 199, 3004 Sep  3 23:05 lvol004
brw-------  1 root root 199, 3003 Sep  3 23:05 lvol003
brw-------  1 root root 199, 3002 Sep  3 23:05 lvol002
brw-------  1 root root 199, 3001 Sep  3 23:05 lvol001
brw-------  1 root root 199, 3000 Sep  3 23:05 lvol000


so I see two naming options here:
either translate to dg1603_lvol001 
but if mounted I would rather like srv_oracle_bestindw_admin
not sure who much overhead this is.
But since on the web interface it's presented under the mountpoint the info is already there which mountpoint it is.

**Comment by h0lzi** [comment]
Adding manual rename in general might not be a bad thing.
For my use case it's not helping much. so having a translation to DISKGROUP_VOLUME Name would help more.
As in parsing /dev/vx/dsk/*

**Comment by ktsaou** [comment]
Could you please post the output of this:

```sh
tree /dev/vx/disk/
```

I am not sure what can be extracted from this, so the above will give me a better picture.

**Comment by h0lzi** [comment]
nee tree on Suse System :(
z1tl9460:/dev/vx/dsk # find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
.
|____dg4684
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4699
| |____lvol004
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4698
| |____lvol004
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4697
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4696
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4695
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4694
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4693
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4692
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4690
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4689
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4688
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4687
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4686
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4685
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4671
| |____lvol004
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4670
| |____lvol004
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4669
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4668
| |____lvol000
| |____lvol003
| |____lvol002
| |____lvol001
|____dg4666
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4665
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4664
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4663
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4662
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____dg4660
| |____lvol004
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000
|____appvg
| |____lvol001
| |____lvol000
|____dg50
| |____lvol000


and the lvol011 are the block devices you can match.
z1tl9460:/dev/vx/dsk/appvg # ls -alrth
total 0
brw-------  1 root root 199, 6001 Jun  8 03:25 lvol001
brw-------  1 root root 199, 6000 Jun  8 03:25 lvol000
drwxr-xr-x  2 root root        80 Jun  8 03:25 .
drwxr-xr-x 29 root root       580 Aug 27 19:24 ..
z1tl9460:/dev/vx/dsk/appvg # grep 6001 /proc/diskstats 
 128      64 sdec 450523 10125 3795288 610604 89 0 2048 180 0 600140 610356
 199    6001 VxVM6001 2408961 161216 161729497 2274996 6508302 553159 308697979 2082032 0 1484576 4437908

**Comment by ktsaou** [comment]
So, you are saying that netdata should get major:minor from `/proc/diskstats` (in our case `199:6001` and then read the directory `/dev/vx/dsk/appvg` to search for a block device with the same major:minor, and when found, use the filename of that file, to name the disk.

So, for `VcVM6001` the name should be `lvol001`. Right?

The only problem I see is that netdata does not run as root by default. So, reading `/dev/vx/dsk/appvg` will not work, unless you run netdata as root.

**Comment by ktsaou** [comment]
No, my bad. The directory must be readable by normal users. Can you verify you can run this as a normal user:

```sh
ls -l /dev/vx/dsk/appvg
```

**Comment by h0lzi** [comment]
I can read it as a normal user:
1tl9460 ___ /dev/vx/dsk/appvg $ id -a
uid=778(oracle) gid=777(oinstall) groups=777(oinstall),42(trusted)
z1tl9460 ___ /dev/vx/dsk/appvg $ ls -alrth
total 0
brw-------  1 root root 199, 6001 Jun  8 03:25 lvol001
brw-------  1 root root 199, 6000 Jun  8 03:25 lvol000
drwxr-xr-x  2 root root        80 Jun  8 03:25 .
drwxr-xr-x 29 root root       580 Aug 27 19:24 ..


in this example I would like  VxVM6001 be named appvg_lvol001 
as lvol001 on it's own is not uniq.

**Comment by ktsaou** [comment]
Yes, probably `vx_appvg_lvol001`.

**Comment by ktsaou** [comment]
ok, you can find it at PR #4150 
Can you test it?

**Comment by h0lzi** [comment]
Hi,
thanks for that. But I probably created some misunderstanding.

appvg is an arbitrary name for one diskgroup. As you see in in the tree output above I have also e.g.
|____dg4660
| |____lvol004
| |____lvol003
| |____lvol002
| |____lvol001
| |____lvol000

so would needs to be done is to parse /dev/vx/dsk/*/* and build the names from that.
so we have vx_appvg_lvol001
and vx_ dg4660_lvol001 and so on.
Sorry that I did not make that clear.
Thank you for you time to look at some exotic stuff :)

**Comment by ktsaou** [comment]
Sorry, I still don't get it.

Let's go step by step:

1. netdata reads /proc/diskstats
2. there it finds `199    6001 VxVM6001 ...`
3. it looks at `/dev/vx/dsk/appvg` to find a block device with major 199 and minor 6001. If finds it:

```
brw-------  1 root root 199, 6001 Jun  8 03:25 lvol001
```

4. So, it names the disk `vx_appvg_lvol001`.

What is `dg4460` and how it should be used?

**Comment by h0lzi** [comment]
I don't have the system in front of me so I make up the minor numbers here:

Flow should be:
1. netdata reads /proc/diskstats
2. there it finds 199 6001 VxVM6001 
                            199 6002 VxVM6002
                            199 3001 VxVM3001....
3. look through tree of /dev/vx/dsk/*

and finds /dev/vx/dsk/appvg/lvol001  being  6001
and           /dev/vx/dsk/appvg/lvol002 beeing 6002
so names that disk vx_appvg_lvol001 and vx_appvg_lvol002

also finds /dev/vx/dsk/dg4660/examplevolume being 3001
so names the disk vx_dg4660_examplevolume

in LVM terms iirc
The folder structure is:
/dev/vx/dsk/$VOLUMEGROUP/$VOLUME

both are arbitrary Names that the admin assigns. 

Hope this helps. 
Otherwise I will try to explain it again tomorrow after a fresh coffee :)

**Comment by ktsaou** [comment]
hm... I still don't get it.

I understand `lvol001` will appear under many `dg46XX` (it does on the output you provides above) and all these lvol001 will be matching major:minor numbers. So what netdata should do? Walk through all of them and append `dg46XX` many times to the name of the disk?

I am probably missing something here...

**Comment by Ferroin** [comment]
As I understand it, using an analogy from LVM:

* The `dg*` directories are volume groups in LVM terms.
* The `lvol*` device nodes are logical volumes in LVM terms.

So, presentation should work similarly to how we present LVM volumes, just using the Veritas Volume Manager directory structure for the lookups.

**Comment by ktsaou** [comment]
It depends on what each volume manager lists in `/proc/diskstats` (since this is what the system thinks its disks are).

So, if logical volumes are listed, instead of `/dev/mapper` of VLM, veritas uses `/dev/vx/dsk/appvg` to name them.

I am not sure if naming volume groups is needed.

**Comment by h0lzi** [comment]
Hi, ok with some fresh coffe let's try to explain it again.

what @Ferroin said is mostly what I try to explain.
Just that there is some difference.
For LVM you parse /dev/mapper which already has the same you present I guess:

e.g.

z1tl9165:/dev/rootvg # cd /dev/mapper/
z1tl9165:/dev/mapper # ls -larth *root_lv
lrwxrwxrwx 1 root root 7 Sep  3 22:58 rootvg-root_lv -> ../dm-3

z1tl9165:/dev/mapper # grep dm-3 /proc/diskstats 
 253       3 dm-3 28981 0 3370032 70084 333556 0 2668448 16197988 0 906548 16269228

So dm-3 is named rootvg_root_lv

so /dev/mapper already joins volumegroup and volume name.

There is also an "old" way presented in /dev without mapper:
That is for this volumes:

/dev/rootvg/root_lv

z1tl9165:/dev/mapper # ls -larth /dev/rootvg/root_lv 
lrwxrwxrwx 1 root root 7 Sep  3 22:58 /dev/rootvg/root_lv -> ../dm-3


So Veritas does have this some "old" approch to have a directory for each Volumegroup/Diskgroup
and the list of  volumes belonging to that Group underneath it.

So let's take a few examples:

z1tl9165:/dev/mapper # grep VxVM /proc/diskstats |head
 199   23000 VxVM23000 827954 93006 203013701 845476 1938614 89676 177079827 1234336 0 1588412 2095456
 199   23001 VxVM23001 49672 2437 1432060 22608 479624 32488 15215110 577840 0 151096 607040
 199   18000 VxVM18000 47058 2 259828 59116 891 2 4736 936 0 59860 60000
 199   12000 VxVM12000 47033 2 259220 32484 898 2 4894 912 0 33280 33360


z1tl9165:/dev/mapper # ls -larth /dev/vx/dsk/*/* |grep 23000
brw------- 1 root root 199, 23000 Sep  3 23:00 /dev/vx/dsk/appvg/lvol000

z1tl9165:/dev/mapper # ls -larth /dev/vx/dsk/*/* |grep 23001
brw------- 1 root root 199, 23001 Sep  3 23:00 /dev/vx/dsk/appvg/lvol001

z1tl9165:/dev/mapper # ls -larth /dev/vx/dsk/*/* |grep 18000
brw------- 1 root root 199, 18000 Sep  3 23:04 /dev/vx/dsk/dg1600/lvol000

z1tl9165:/dev/mapper # ls -larth /dev/vx/dsk/*/* |grep 12000
brw------- 1 root root 199, 12000 Sep  3 23:05 /dev/vx/dsk/dg1601/lvol000


So in this example I would like to have
VxVM23000 be named vx_appvg_lvol000
VxVM23001 be named vx_appvg_lvol001
VxVM18000 be named vx_dg1600_lvol000
VxVM12000 be named vx_dg1601_lvol000

So for naming you need to include the name of the directory the volume is in. So that you have uniq names and make it clear to which diskgroup/volumegroup the volume belongs too.

Hope this helps

**Comment by ktsaou** [comment]
ok, here it is.
Could you please test it?

**Comment by h0lzi** [comment]
thx will try as soon as I have the time to build it.

**Comment by h0lzi** [comment]
hmm.
it seem to do something:
018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sda', 8:0): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path.
2018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sda1', 8:1): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path.
2018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sda2', 8:2): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path. (errno 2, No such file or directory)
2018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sda3', 8:3): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path. (errno 2, No such file or directory)
2018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sdb', 8:16): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path. (errno 2, No such file or directory)
2018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sdb3', 8:19): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path.
2018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sdb8', 8:24): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path. (errno 2, No such file or directory)
2018-09-12 11:28:15: netdata ERROR : PLUGIN[proc] : (0328@proc_disks:get_disk_name_f): DEVICE-MAPPER ('sdd', 8:48): Depth limit reached for path '/dev/vx/dsk/'. Ignoring path. (errno 2, No such file or directory)


but disks are not renamed.

**Comment by ktsaou** [comment]
ok, this is strange.
I added some debugging info to trace it. Could you please retry and post all the lines with `DEVICE-MAPPER`?

If the log flood protection kicks in, please edit `netdata.conf` and increase a bit `errors to trigger flood protection`, to have them all.

**Comment by h0lzi** [comment]
ok maybe my error trigger kicked in just to early.
So we have this

2018-09-12 14:33:26: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): filename '/dev/mapper/../dm-7' does not match 253:7.
2018-09-12 14:33:26: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): examining directory '/dev/disk/by-label' (allowed depth 0).
2018-09-12 14:33:26: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): filename '/dev/disk/by-label/../../dm-9' does not match 253:9.
2018-09-12 14:33:26: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): examining directory '/dev/vx/dsk/' (allowed depth 0).
2018-09-12 14:33:26: netdata ERROR : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): Depth limit reached for path '/dev/vx/dsk//dgt1001'. Ignoring path.

so it bails out looking.

ibmtverc01tlx:~ # ls -larth /dev/vx/dsk/*
/dev/vx/dsk/testvg:
total 0
brw------- 1 root root 199, 8000 Aug 31 13:43 testvol
drwxr-xr-x 2 root root        60 Aug 31 13:43 .
drwxr-xr-x 5 root root       100 Aug 31 13:56 ..

/dev/vx/dsk/appdg:
total 0
brw------- 1 root root 199, 7000 Aug 31 13:43 lvoracle
drwxr-xr-x 2 root root        60 Aug 31 13:43 .
drwxr-xr-x 5 root root       100 Aug 31 13:56 ..

/dev/vx/dsk/dgt1001:
total 0
brw------- 1 root root 199, 16004 Aug 31 13:56 lvol004
brw------- 1 root root 199, 16003 Aug 31 13:56 lvol003
brw------- 1 root root 199, 16002 Aug 31 13:56 lvol002
brw------- 1 root root 199, 16001 Aug 31 13:56 lvol001
brw------- 1 root root 199, 16000 Aug 31 13:56 lvol000

should have found 
/dev/vx/dsk/dgt1001/lvol004

**Comment by ktsaou** [comment]
ok, my bad. I should have find it before. Sorry.

It should work now. Debugging is still enabled, so please post again these lines.

**Comment by h0lzi** [comment]
Ok works after fixing one small bug:
proc_diskstat 
https://github.com/firehol/netdata/blob/c8c40a9864117c08c374bee9e75deede08e079fc/src/proc_diskstats.c#L829

appvg needs to be removed.

then I have:
2018-09-13 09:21:23: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): examining directory '/dev/disk/by-label' (allowed depth 0).
2018-09-13 09:21:23: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): filename '/dev/disk/by-label/../../dm-9' does not match 253:9.
2018-09-13 09:21:23: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): examining directory '/dev/vx/dsk/' (allowed depth 2).
2018-09-13 09:21:23: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): examining directory '/dev/vx/dsk//dgt1001' (allowed depth 1).
2018-09-13 09:21:23: netdata INFO  : PLUGIN[proc] : DEVICE-MAPPER ('VxVM16004', 199:16004): filename '/dev/vx/dsk//dgt1001/lvol004' matches.

So machting works the naming is a litlle bit off though it now e.g.

disk.vxvxdgt1001lvol004

so getting rid of one vx and having _ as a delimiter would be nice.
But except that it looks like it's working.

**Comment by ktsaou** [comment]
ok, nice!
fixed them. Could you please retry once more before merging it, to verify everything is good?

**Comment by h0lzi** [comment]
Sorry for not being precise enough:
Works it's now named: disk_ops.vx_dgt1001lvol004

would also love to have _ between diskgroup and volume.
so should be disk_ops.vx_dgt1001_lvol004

also one more questions. Are the metrics forwarded to my configured backend via this name now?
Because in the matrics store I still see VxVM names?

ibmtverc01tlx:/opt/netdata/netdata-metrics # ls -ld *VxVM16004*
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_avgsz.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_await.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_backlog.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_iotime.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_mops.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_ops.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_svctm.VxVM16004
drwxrwx--- 2 netdata netdata 4096 Sep 13 09:41 disk_util.VxVM16004

**Comment by ktsaou** [comment]
> would also love to have _ between diskgroup and volume.
> so should be disk_ops.vx_dgt1001_lvol004

It should be like that. It is the same code that adds `_` after `vx` that adds it after all components. Are you sure it does not?

> also one more questions. Are the metrics forwarded to my configured backend via this name now?

Yes, this is controlled by the following in `netdata.conf`:

```
[backend]
	# send names instead of ids = yes
```

> Because in the matrics store I still see VxVM names?

Is it possible they are old?

**Comment by ktsaou** [comment]
> It should be like that. It is the same code that adds `_` after `vx` that adds it after all components. Are you sure it does not?

my bad. found it. please wait...

**Comment by ktsaou** [comment]
it should be ok now. It was adding `_` to all directories traversed, but it was not adding it to before the final block device found.

**Comment by h0lzi** [comment]
looks good now. Thank you very much. Need to wait for a college to check the backend.

**Comment by ktsaou** [comment]
Thanks! I am merging it.

Do you have the new metrics in the backend?
If yes, then the others are old ones.
