### ISSUE TITLE
Accessing Net Data through port 80 with Apache

### ISSUE THREAD

**Issue by timtjtim** [firehol/netdata#787]
I have an apache server running behind a router that only has port 80 and port 443 open.

This means I cannot see the graphs from other computers. Is there a way to run net data on port 19999, but redirect it's data out through 80?

**Comment by ktsaou** [comment]
Have you checked this: https://github.com/firehol/netdata/wiki/Running-behind-apache ?

**Comment by timtjtim** [comment]
@ktsaou Yes, and I implemented it but that allows access to the full page. I'd like a custom configuration. Do I just change the

    <script type="text/javascript" src="http://127.0.0.1:19999/dashboard.js"></script>

to 

    <script type="text/javascript" src="http://website.tk/NetData"></script>

in the header of the custom file?

**Comment by ktsaou** [comment]
Yes.

**Comment by timtjtim** [comment]
Thanks, that all works now. But, I would like to prevent access to the full dashboard - currently, it is live at http://website.tk/NetData/X - how can I prevent anyone from accessing this?

I tried the basic auth, but of course, that blocks the custom page without login.

Next, I tried the Apache block:

    <Directory /NetData/X/*>
        Order allow,deny
        Deny from all
    </Directory>

but I can still load it. I do have the mod enabled.

**Comment by ktsaou** [comment]
You have to check your web server documentation. Normally you need to prevent `index.html` or `/` from being accessed directly.

Keep in mind though, that the API you custom dashboard is accessing and the API the default dashboard is accessing is the same. So, I could for example edit `index.html` on my netdata to access the API of your netdata server and I'll still get the full dashboard, even if your web server does not allow direct access to `index.html` or `/`.

**Comment by timtjtim** [comment]
That's a good point. I'll just leave it available - and I take it there are no security risks from that?

**Comment by ktsaou** [comment]
> and I take it there are no security risks from that?

Security risks always exist. Check #164

**Comment by ktsaou** [comment]
Is something pending? Shall we close this?
